const LOCALES = ['fr', 'en', 'de', 'es', 'pt', 'it', 'nl'];

const DEMONYMS = {
  CH:  { fr: 'suisse',       en: 'Swiss',        de: 'Schweizer',   es: 'suizo',       pt: 'suíço',       it: 'svizzero',    nl: 'Zwitsers' },
  AF:  { fr: 'afghane',      en: 'Afghan',       de: 'Afghane',     es: 'afgano',      pt: 'afegão',      it: 'afghano',     nl: 'Afghaans' },
  ZA:  { fr: 'sud-africaine',en: 'South African',de: 'Südafrikaner',es: 'sudafricano',  pt: 'sul-africano', it: 'sudafricano',  nl: 'Zuid-Afrikaans' },
  AL:  { fr: 'albanaise',    en: 'Albanian',     de: 'Albaner',     es: 'albanés',     pt: 'albanês',     it: 'albanese',    nl: 'Albanees' },
  DZ:  { fr: 'algérienne',   en: 'Algerian',     de: 'Algerier',    es: 'argelino',    pt: 'argelino',    it: 'algerino',    nl: 'Algerijns' },
  DE:  { fr: 'allemande',    en: 'German',       de: 'Deutscher',   es: 'alemán',      pt: 'alemão',      it: 'tedesco',     nl: 'Duits' },
  AD:  { fr: 'andorrane',    en: 'Andorran',     de: 'Andorraner',  es: 'andorrano',   pt: 'andorrano',   it: 'andorrano',   nl: 'Andorrees' },
  AO:  { fr: 'angolaise',    en: 'Angolan',      de: 'Angolaner',   es: 'angolano',    pt: 'angolano',    it: 'angolano',    nl: 'Angolees' },
  AG:  { fr: 'antiguaise',   en: 'Antiguan',     de: 'Antiguaner',  es: 'antiguano',   pt: 'antiguano',   it: 'antiguano',   nl: 'Antiguaans' },
  SA:  { fr: 'saoudienne',   en: 'Saudi',        de: 'Saudi',       es: 'saudí',       pt: 'saudita',     it: 'saudita',     nl: 'Saoedi' },
  AR:  { fr: 'argentine',    en: 'Argentine',    de: 'Argentinier', es: 'argentino',   pt: 'argentino',   it: 'argentino',   nl: 'Argentijns' },
  AM:  { fr: 'arménienne',   en: 'Armenian',     de: 'Armenier',    es: 'armenio',     pt: 'armênio',     it: 'armeno',      nl: 'Armeens' },
  AU:  { fr: 'australienne', en: 'Australian',   de: 'Australier',  es: 'australiano', pt: 'australiano', it: 'australiano', nl: 'Australisch' },
  AT:  { fr: 'autrichienne', en: 'Austrian',     de: 'Österreicher',es: 'austriaco',   pt: 'austríaco',   it: 'austriaco',   nl: 'Oostenrijks' },
  AZ:  { fr: 'azerbaïdjanaise',en:'Azerbaijani', de: 'Aserbaidschaner',es:'azerbaiyano',pt:'azerbaijano',it:'azero',       nl: 'Azerbeidzjaans' },
  BS:  { fr: 'bahamienne',   en: 'Bahamian',     de: 'Bahamaer',    es: 'bahameño',    pt: 'bahamense',   it: 'bahamiano',   nl: 'Bahamaans' },
  BH:  { fr: 'bahreïnienne', en: 'Bahraini',     de: 'Bahrainer',   es: 'bareiní',     pt: 'bareinita',   it: 'bahreinita',  nl: 'Bahreins' },
  BD:  { fr: 'bangladeshie', en: 'Bangladeshi',  de: 'Bangladescher',es:'bangladesí',  pt:'bangladês',    it:'bengalese',   nl:'Bengalees'},
  BB:  { fr: 'barbadienne',  en: 'Barbadian',    de: 'Barbadier',   es: 'barbadense',  pt: 'barbadiano',  it: 'barbadiano',  nl: 'Barbadiaans' },
  BE:  { fr: 'belge',        en: 'Belgian',      de: 'Belgier',     es: 'belga',       pt: 'belga',       it: 'belga',       nl: 'Belgisch' },
  BZ:  { fr: 'bélizienne',   en: 'Belizean',     de: 'Belizer',     es: 'beliceño',    pt: 'belizenho',   it: 'beliziano',   nl: 'Belizisch' },
  BJ:  { fr: 'béninoise',    en: 'Beninese',     de: 'Beniner',     es: 'beninés',     pt: 'beninense',   it: 'beninese',    nl: 'Benins' },
  BT:  { fr: 'bhoutanaise',  en: 'Bhutanese',    de: 'Bhutaner',    es: 'butanés',     pt: 'butanês',     it: 'bhutanese',   nl: 'Bhutaans' },
  BY:  { fr: 'biélorusse',   en: 'Belarusian',   de: 'Belaruse',    es: 'bielorruso',  pt: 'bielorrusso', it: 'bielorusso',  nl: 'Wit-Russisch' },
  MM:  { fr: 'birmane',      en: 'Burmese',      de: 'Myanmare',    es: 'birmano',     pt: 'birmanês',    it: 'birmano',     nl: 'Birmaans' },
  BO:  { fr: 'bolivienne',   en: 'Bolivian',     de: 'Bolivianer',  es: 'boliviano',   pt: 'boliviano',   it: 'boliviano',   nl: 'Boliviaans' },
  BA:  { fr: 'bosnienne',    en: 'Bosnian',      de: 'Bosnier',     es: 'bosnio',      pt: 'bósnio',      it: 'bosniaco',    nl: 'Bosnisch' },
  BW:  { fr: 'botswanaise',  en: 'Botswanan',    de: 'Botswaner',   es: 'botsuano',    pt: 'botsuanês',   it: 'botswano',    nl: 'Botswaans' },
  BR:  { fr: 'brésilienne',  en: 'Brazilian',    de: 'Brasilianer', es: 'brasileño',   pt: 'brasileiro',  it: 'brasiliano',  nl: 'Braziliaans' },
  BN:  { fr: 'brunéienne',   en: 'Bruneian',     de: 'Bruneier',    es: 'bruneano',    pt: 'bruneano',    it: 'bruneano',    nl: 'Bruneis' },
  BG:  { fr: 'bulgare',      en: 'Bulgarian',    de: 'Bulgare',     es: 'búlgaro',     pt: 'búlgaro',     it: 'bulgaro',     nl: 'Bulgaars' },
  BF:  { fr: 'burkinabée',   en: 'Burkinabe',    de: 'Burkiner',    es: 'burquinés',   pt: 'burquinense', it: 'burkinabè',   nl: 'Burkinees' },
  BI:  { fr: 'burundaise',   en: 'Burundian',    de: 'Burundier',   es: 'burundés',    pt: 'burundiano',  it: 'burundiano',  nl: 'Burundees' },
  CV:  { fr: 'cap-verdienne',en: 'Cape Verdean', de: 'Kapverdier',  es: 'caboverdiano',pt:'cabo-verdiano',it:'capoverdiano',nl:'Kaapverdisch'},
  KH:  { fr: 'cambodgienne', en: 'Cambodian',    de: 'Kambodschaner',es:'camboyano',   pt:'cambojano',    it:'cambogiano',   nl:'Cambodjaans'},
  CM:  { fr: 'camerounaise', en: 'Cameroonian',  de: 'Kameruner',   es: 'camerunés',   pt: 'camaronês',   it: 'camerunense', nl: 'Kameroens' },
  CA:  { fr: 'canadienne',   en: 'Canadian',     de: 'Kanadier',    es: 'canadiense',  pt: 'canadense',   it: 'canadese',    nl: 'Canadees' },
  CL:  { fr: 'chilienne',    en: 'Chilean',      de: 'Chilene',     es: 'chileno',     pt: 'chileno',     it: 'cileno',      nl: 'Chileens' },
  CN:  { fr: 'chinoise',     en: 'Chinese',      de: 'Chinese',     es: 'chino',       pt: 'chinês',      it: 'cinese',      nl: 'Chinees' },
  CY:  { fr: 'chypriote',    en: 'Cypriot',      de: 'Zypriot',     es: 'chipriota',   pt: 'cipriota',    it: 'cipriota',    nl: 'Cypriotisch' },
  CO:  { fr: 'colombienne',  en: 'Colombian',    de: 'Kolumbianer', es: 'colombiano',  pt: 'colombiano',  it: 'colombiano',  nl: 'Colombiaans' },
  KM:  { fr: 'comorienne',   en: 'Comorian',     de: 'Komorer',     es: 'comorense',   pt: 'comorense',   it: 'comoriano',   nl: 'Comorees' },
  CG:  { fr: 'congolaise',   en: 'Congolese',    de: 'Kongolese',   es: 'congoleño',   pt: 'congolês',    it: 'congolese',   nl: 'Congolees' },
  CD:  { fr: 'congolaise',   en: 'Congolese',    de: 'Kongolese',   es: 'congoleño',   pt: 'congolês',    it: 'congolese',   nl: 'Congolees' },
  KP:  { fr: 'nord-coréenne',en: 'North Korean', de: 'Nordkoreaner',es:'norcoreano',   pt:'norte-coreano',it:'nordcoreano', nl:'Noord-Koreaans'},
  KR:  { fr: 'sud-coréenne', en: 'South Korean', de: 'Südkoreaner', es:'surcoreano',   pt:'sul-coreano',  it:'sudcoreano',  nl:'Zuid-Koreaans'},
  CR:  { fr: 'costaricienne',en: 'Costa Rican',  de: 'Costa-Ricaner',es:'costarricense',pt:'costarriquenho',it:'costaricano',nl:'Costa Ricaans'},
  CI:  { fr: 'ivoirienne',   en: 'Ivorian',      de: 'Ivorer',      es: 'marfileño',   pt: 'marfinense',  it: 'ivoriano',    nl: 'Ivoriaans' },
  HR:  { fr: 'croate',       en: 'Croatian',     de: 'Kroate',      es: 'croata',      pt: 'croata',      it: 'croato',      nl: 'Kroatisch' },
  CU:  { fr: 'cubaine',      en: 'Cuban',        de: 'Kubaner',     es: 'cubano',      pt: 'cubano',      it: 'cubano',      nl: 'Cubaans' },
  DK:  { fr: 'danoise',      en: 'Danish',       de: 'Däne',        es: 'danés',       pt: 'dinamarquês', it: 'danese',      nl: 'Deens' },
  DJ:  { fr: 'djiboutienne', en: 'Djiboutian',   de: 'Dschibutier', es: 'yibutiano',   pt: 'djibutiense', it: 'gibutiano',   nl: 'Djiboutiaans' },
  DM:  { fr: 'dominiquaise', en: 'Dominican',    de: 'Dominicaner', es: 'dominiqués',  pt: 'dominiquense',it:'dominichese', nl:'Dominicaans'},
  EG:  { fr: 'égyptienne',   en: 'Egyptian',     de: 'Ägypter',     es: 'egipcio',     pt: 'egípcio',     it: 'egiziano',    nl: 'Egyptisch' },
  AE:  { fr: 'émiratie',     en: 'Emirati',      de: 'Emirater',    es: 'emiratí',     pt: 'emirático',   it: 'emiratino',   nl: 'Emiraats' },
  EC:  { fr: 'équatorienne', en: 'Ecuadorian',   de: 'Ecuadorianer',es:'ecuatoriano',  pt:'equatoriano',  it:'ecuadoriano', nl:'Ecuadoraans'},
  ER:  { fr: 'érythréenne',  en: 'Eritrean',     de: 'Eritreer',    es: 'eritreo',     pt: 'eritreu',     it: 'eritreo',     nl: 'Eritrees' },
  ES:  { fr: 'espagnole',    en: 'Spanish',      de: 'Spanier',     es: 'español',     pt: 'espanhol',    it: 'spagnolo',    nl: 'Spaans' },
  EE:  { fr: 'estonienne',   en: 'Estonian',     de: 'Este',        es: 'estonio',     pt: 'estoniano',   it: 'estone',      nl: 'Ests' },
  SZ:  { fr: 'swazie',       en: 'Swazi',        de: 'Swasiländer', es: 'suazi',       pt: 'suazi',       it: 'swazi',       nl: 'Swazisch' },
  US:  { fr: 'américaine',   en: 'American',     de: 'Amerikaner',  es: 'estadounidense',pt:'americano',   it:'american',   nl:'Amerikaans'},
  ET:  { fr: 'éthiopienne',  en: 'Ethiopian',    de: 'Äthiopier',   es: 'etíope',      pt: 'etíope',      it: 'etiope',      nl: 'Ethiopisch' },
  FJ:  { fr: 'fidjienne',    en: 'Fijian',       de: 'Fidschianer', es: 'fiyiano',     pt: 'fijiano',     it: 'figiano',     nl: 'Fijisch' },
  FI:  { fr: 'finlandaise',  en: 'Finnish',      de: 'Finne',       es: 'finlandés',   pt: 'finlandês',   it: 'finlandese',  nl: 'Fins' },
  FR:  { fr: 'française',    en: 'French',       de: 'Franzose',    es: 'francés',     pt: 'francês',     it: 'francese',    nl: 'Frans' },
  GA:  { fr: 'gabonaise',    en: 'Gabonese',     de: 'Gabuner',     es: 'gabonés',     pt: 'gabonense',   it: 'gabonese',    nl: 'Gabonees' },
  GM:  { fr: 'gambienne',    en: 'Gambian',      de: 'Gambier',     es: 'gambiano',    pt: 'gambiano',    it: 'gambiano',    nl: 'Gambiaans' },
  GE:  { fr: 'géorgienne',   en: 'Georgian',     de: 'Georgier',    es: 'georgiano',   pt: 'georgiano',   it: 'georgiano',   nl: 'Georgisch' },
  GH:  { fr: 'ghanéenne',    en: 'Ghanaian',     de: 'Ghanaer',     es: 'ghanés',      pt: 'ganês',       it: 'ghanese',     nl: 'Ghanees' },
  GR:  { fr: 'grecque',      en: 'Greek',        de: 'Grieche',     es: 'griego',      pt: 'grego',       it: 'greco',       nl: 'Grieks' },
  GD:  { fr: 'grenadienne',  en: 'Grenadian',    de: 'Grenader',    es: 'granadino',   pt: 'granadino',   it: 'grenadino',   nl: 'Grenadiaans' },
  GT:  { fr: 'guatémaltèque',en: 'Guatemalan',   de: 'Guatemalteke',es:'guatemalteco', pt:'guatemalteco', it:'guatemalteco', nl:'Guatemalteeks'},
  GN:  { fr: 'guinéenne',    en: 'Guinean',      de: 'Guineer',     es: 'guineano',    pt: 'guineano',    it: 'guineano',    nl: 'Guinees' },
  GQ:  { fr: 'guinéenne-équatoriale',en:'Equatorial Guinean',de:'Äquatorialguineer',es:'ecuatoguineano',pt:'guinéu-equatoriano',it:'equatoguineano',nl:'Equatoriaal-Guinees'},
  GW:  { fr: 'guinéenne-bissau',en:'Bissau-Guinean',de:'Bissauer', es: 'bisauguineano',pt:'guineense',   it:'bissauiano',   nl:'Guinee-Bissaus'},
  GY:  { fr: 'guyanaise',    en: 'Guyanese',     de: 'Guyaner',     es: 'guyanés',     pt: 'guianense',   it: 'guyanese',    nl: 'Guyanees' },
  HT:  { fr: 'haïtienne',    en: 'Haitian',      de: 'Haitianer',   es: 'haitiano',    pt: 'haitiano',    it: 'haitiano',    nl: 'Haïtiaans' },
  HN:  { fr: 'hondurienne',  en: 'Honduran',     de: 'Honduraner',  es: 'hondureño',   pt: 'hondurenho',  it: 'honduregno',  nl: 'Hondurees' },
  HU:  { fr: 'hongroise',    en: 'Hungarian',    de: 'Ungar',       es: 'húngaro',     pt: 'húngaro',     it: 'ungherese',   nl: 'Hongaars' },
  IN:  { fr: 'indienne',     en: 'Indian',       de: 'Inder',       es: 'indio',       pt: 'indiano',     it: 'indiano',     nl: 'Indiaas' },
  ID:  { fr: 'indonésienne', en: 'Indonesian',   de: 'Indonesier',  es: 'indonesio',   pt: 'indonésio',   it: 'indonesiano', nl: 'Indonesisch' },
  IR:  { fr: 'iranienne',    en: 'Iranian',      de: 'Iraner',      es: 'iraní',       pt: 'iraniano',    it: 'iraniano',    nl: 'Iraans' },
  IQ:  { fr: 'irakienne',    en: 'Iraqi',        de: 'Iraker',      es: 'iraquí',      pt: 'iraquiano',   it: 'iraqeno',     nl: 'Iraaks' },
  IE:  { fr: 'irlandaise',   en: 'Irish',        de: 'Ire',         es: 'irlandés',    pt: 'irlandês',    it: 'irlandese',   nl: 'Iers' },
  IS:  { fr: 'islandaise',   en: 'Icelander',    de: 'Isländer',    es: 'islandés',    pt: 'islandês',    it: 'islandese',   nl: 'IJslands' },
  IL:  { fr: 'israélienne',  en: 'Israeli',      de: 'Israeli',     es: 'israelí',     pt: 'israelense',  it: 'israeliano',  nl: 'Israëlisch' },
  IT:  { fr: 'italienne',    en: 'Italian',      de: 'Italiener',   es: 'italiano',    pt: 'italiano',    it: 'italiano',    nl: 'Italiaans' },
  JM:  { fr: 'jamaïcaine',   en: 'Jamaican',     de: 'Jamaikaner',  es: 'jamaiquino',  pt: 'jamaicano',   it: 'giamaicano',  nl: 'Jamaicaans' },
  JP:  { fr: 'japonaise',    en: 'Japanese',     de: 'Japaner',     es: 'japonés',     pt: 'japonês',     it: 'giapponese',  nl: 'Japans' },
  JO:  { fr: 'jordanienne',  en: 'Jordanian',    de: 'Jordanier',   es: 'jordano',     pt: 'jordaniano',  it: 'giordano',    nl: 'Jordaans' },
  KZ:  { fr: 'kazakhe',      en: 'Kazakh',       de: 'Kasache',     es: 'kazajo',      pt: 'cazaque',     it: 'kazako',      nl: 'Kazachs' },
  KE:  { fr: 'kenyane',      en: 'Kenyan',       de: 'Kenianer',    es: 'keniano',     pt: 'queniano',    it: 'keniota',     nl: 'Keniaans' },
  KI:  { fr: 'kiribatienne', en: 'I-Kiribati',   de: 'Kiribatier',  es: 'kiribatiano', pt: 'kiribatiano', it: 'kiribatese',  nl: 'Kiribatisch' },
  KW:  { fr: 'koweïtienne',  en: 'Kuwaiti',      de: 'Kuwaiti',     es: 'kuwaití',     pt: 'kuwaitiano',  it: 'kuwaitiano',  nl: 'Koeweits' },
  KG:  { fr: 'kirghize',     en: 'Kyrgyz',       de: 'Kirgise',     es: 'kirguís',     pt: 'quirguiz',    it: 'kirghiso',    nl: 'Kirgizisch' },
  LA:  { fr: 'laotienne',    en: 'Lao',          de: 'Laote',       es: 'laosiano',    pt: 'laosiano',    it: 'laotiano',    nl: 'Laotiaans' },
  LS:  { fr: 'lesothane',    en: 'Basotho',      de: 'Lesother',    es: 'lesothense',  pt: 'lesotiano',   it: 'lesothiano',  nl: 'Lesothaans' },
  LV:  { fr: 'lettone',      en: 'Latvian',      de: 'Lette',       es: 'letón',       pt: 'letão',       it: 'lettone',     nl: 'Lets' },
  LB:  { fr: 'libanaise',    en: 'Lebanese',     de: 'Libanese',    es: 'libanés',     pt: 'libanês',     it: 'libanese',    nl: 'Libanees' },
  LR:  { fr: 'libérienne',   en: 'Liberian',     de: 'Liberianer',  es: 'liberiano',   pt: 'liberiano',   it: 'liberiano',   nl: 'Liberiaans' },
  LY:  { fr: 'libyenne',     en: 'Libyan',       de: 'Libyer',      es: 'libio',       pt: 'líbio',       it: 'libico',      nl: 'Libisch' },
  LI:  { fr: 'liechtensteinoise',en:'Liechtensteiner',de:'Liechtensteiner',es:'liechtensteiniano',pt:'liechtensteiniano',it:'liechtensteiniano',nl:'Liechtensteins'},
  LT:  { fr: 'lituanienne',  en: 'Lithuanian',   de: 'Litauer',     es: 'lituano',     pt: 'lituano',     it: 'lituano',     nl: 'Litouws' },
  LU:  { fr: 'luxembourgeoise',en:'Luxembourgish',de:'Luxemburger', es:'luxemburgués', pt:'luxemburguês', it:'lussemburghese',nl:'Luxemburgs'},
  MK:  { fr: 'macédonienne', en: 'Macedonian',   de: 'Mazedonier',  es: 'macedonio',   pt: 'macedônio',   it: 'macedone',    nl: 'Macedonisch' },
  MG:  { fr: 'malgache',     en: 'Malagasy',     de: 'Madagasse',   es: 'malgache',    pt: 'malgaxe',     it: 'malgascio',   nl: 'Malagassisch' },
  MW:  { fr: 'malawienne',   en: 'Malawian',     de: 'Malawier',    es: 'malauí',      pt: 'malauiano',   it: 'malawiano',   nl: 'Malawiaans' },
  MY:  { fr: 'malaisienne',  en: 'Malaysian',    de: 'Malaysier',   es: 'malasio',     pt: 'malaio',      it: 'malese',      nl: 'Maleisisch' },
  MV:  { fr: 'maldivienne',  en: 'Maldivian',    de: 'Malediver',   es: 'maldivo',     pt: 'maldivano',   it: 'maldiviano',  nl: 'Maldivisch' },
  ML:  { fr: 'malienne',     en: 'Malian',       de: 'Mali',        es: 'malí',        pt: 'malinês',     it: 'maliano',     nl: 'Malinees' },
  MT:  { fr: 'maltaise',     en: 'Maltese',      de: 'Malteser',    es: 'maltés',      pt: 'maltês',      it: 'maltese',     nl: 'Maltees' },
  MA:  { fr: 'marocaine',    en: 'Moroccan',     de: 'Marokkaner',  es: 'marroquí',    pt: 'marroquino',  it: 'marocchino',  nl: 'Marokkaans' },
  MH:  { fr: 'marshallaise', en: 'Marshallese',  de: 'Marshaller',  es: 'marshalés',   pt: 'marshalês',   it: 'marshallese', nl: 'Marshallees' },
  MU:  { fr: 'mauricienne',  en: 'Mauritian',    de: 'Mauritier',   es: 'mauriciano',  pt: 'mauriciano',  it: 'mauriziano',  nl: 'Mauritiaans' },
  MR:  { fr: 'mauritanienne',en: 'Mauritanian',  de: 'Mauritanier', es:'mauritano',    pt:'mauritano',    it:'mauritano',    nl:'Mauritaans'},
  MX:  { fr: 'mexicaine',    en: 'Mexican',      de: 'Mexikaner',   es: 'mexicano',    pt: 'mexicano',    it: 'messicano',   nl: 'Mexicaans' },
  FM:  { fr: 'micronésienne',en: 'Micronesian',  de: 'Mikronesier', es:'micronesio',   pt:'micronésio',   it:'micronesian',  nl:'Micronesisch'},
  MD:  { fr: 'moldave',      en: 'Moldovan',     de: 'Moldawier',   es: 'moldavo',     pt: 'moldavo',     it: 'moldavo',     nl: 'Moldavisch' },
  MC:  { fr: 'monégasque',   en: 'Monégasque',   de: 'Monegasse',   es: 'monegasco',   pt: 'monegasco',   it: 'monegasco',   nl: 'Monegaskisch' },
  MN:  { fr: 'mongole',      en: 'Mongolian',    de: 'Mongole',     es: 'mongol',      pt: 'mongol',      it: 'mongolo',     nl: 'Mongools' },
  ME:  { fr: 'monténégrine', en: 'Montenegrin',  de: 'Montenegriner',es:'montenegrino',pt:'montenegrino',it:'montenegrino',nl:'Montenegrijns'},
  MZ:  { fr: 'mozambicaine', en: 'Mozambican',   de: 'Mosambikaner',es:'mozambiqueño', pt:'moçambicano',  it:'mozambicano', nl:'Mozambikaans'},
  NA:  { fr: 'namibienne',   en: 'Namibian',     de: 'Namibier',    es: 'namibio',     pt: 'namibiano',   it: 'namibiano',   nl: 'Namibisch' },
  NR:  { fr: 'nauruanne',    en: 'Nauruan',      de: 'Nauruer',     es: 'nauruano',    pt: 'nauruano',    it: 'nauruano',    nl: 'Nauruaans' },
  NP:  { fr: 'népalaise',    en: 'Nepalese',     de: 'Nepalese',    es: 'nepalí',      pt: 'nepalês',     it: 'nepalese',    nl: 'Nepalees' },
  NI:  { fr: 'nicaraguayenne',en:'Nicaraguan',   de:'Nicaraguaner', es:'nicaragüense', pt:'nicaraguense', it:'nicaraguense', nl:'Nicaraguaans'},
  NE:  { fr: 'nigérienne',   en: 'Nigerien',     de: 'Nigerer',     es: 'nigerino',    pt: 'nigerino',    it: 'nigerino',    nl: 'Nigerees' },
  NG:  { fr: 'nigériane',    en: 'Nigerian',     de: 'Nigerianer',  es: 'nigeriano',   pt: 'nigeriano',   it: 'nigeriano',   nl: 'Nigeriaans' },
  NO:  { fr: 'norvégienne',  en: 'Norwegian',    de: 'Norweger',    es: 'noruego',     pt: 'norueguês',   it: 'norvegese',   nl: 'Noors' },
  NC:  { fr: 'néo-calédonienne',en:'New Caledonian',de:'Neukaledonier',es:'neocaledonio',pt:'neocaledônio',it:'neocaledoniano',nl:'Nieuw-Caledonisch'},
  NZ:  { fr: 'néo-zélandaise',en: 'New Zealander',de:'Neuseeländer',es:'neozelandés',  pt:'neozelandês',  it:'neozelandese', nl:'Nieuw-Zeelands'},
  OM:  { fr: 'omanaise',     en: 'Omani',        de: 'Omaner',      es: 'omaní',       pt: 'omaniano',    it: 'omanita',     nl: 'Omaans' },
  UG:  { fr: 'ougandaise',   en: 'Ugandan',      de: 'Ugander',     es: 'ugandés',     pt: 'ugandense',   it: 'ugandese',    nl: 'Oegandees' },
  UZ:  { fr: 'ouzbèke',      en: 'Uzbek',        de: 'Usbeke',      es: 'uzbeko',      pt: 'uzbeque',     it: 'uzbeko',      nl: 'Oezbeeks' },
  PK:  { fr: 'pakistanaise', en: 'Pakistani',    de: 'Pakistaner',  es: 'paquistaní',  pt: 'paquistanês', it: 'pakistano',   nl: 'Pakistaans' },
  PW:  { fr: 'palaosienne',  en: 'Palauan',      de: 'Palauer',     es: 'palauano',    pt: 'palauano',    it: 'palauano',    nl: 'Palaus' },
  PS:  { fr: 'palestinienne',en: 'Palestinian',  de: 'Palästinenser',es:'palestino',   pt:'palestino',    it:'palestinese',  nl:'Palestijns'},
  PA:  { fr: 'panaméenne',   en: 'Panamanian',   de: 'Panamaer',    es: 'panameño',    pt: 'panamenho',   it: 'panamense',   nl: 'Panamees' },
  PG:  { fr: 'papouasienne', en: 'Papua New Guinean',de:'Papua-Neuguineer',es:'papú',    pt:'papuásio',     it:'papuan',      nl:'Papoea-Nieuw-Guinees'},
  PY:  { fr: 'paraguayenne', en: 'Paraguayan',   de: 'Paraguayer',  es: 'paraguayo',   pt: 'paraguaio',   it: 'paraguaiano', nl: 'Paraguayaans' },
  NL:  { fr: 'néerlandaise', en: 'Dutch',        de: 'Niederländer',es:'neerlandés',   pt:'neerlandês',   it:'olandese',     nl:'Nederlands'},
  PE:  { fr: 'péruvienne',   en: 'Peruvian',     de: 'Peruaner',    es: 'peruano',     pt: 'peruano',     it: 'peruviano',   nl: 'Peruaans' },
  PH:  { fr: 'philippine',   en: 'Filipino',     de: 'Filipino',    es: 'filipino',    pt: 'filipino',    it: 'filippino',   nl: 'Filipijns' },
  PL:  { fr: 'polonaise',    en: 'Polish',       de: 'Pole',        es: 'polaco',      pt: 'polonês',     it: 'polacco',     nl: 'Pools' },
  PT:  { fr: 'portugaise',   en: 'Portuguese',   de: 'Portugiese',  es: 'portugués',   pt: 'português',   it: 'portoghese',  nl: 'Portugees' },
  QA:  { fr: 'qatarienne',   en: 'Qatari',       de: 'Katarer',     es: 'catarí',      pt: 'catariano',   it: 'qatariota',   nl: 'Qatarees' },
  CF:  { fr: 'centrafricaine',en:'Central African',de:'Zentralafrikaner',es:'centroafricano',pt:'centro-africano',it:'centrafricano',nl:'Centraal-Afrikaans'},
  DO:  { fr: 'dominicaine',  en: 'Dominican',    de: 'Dominikaner', es:'dominicano',   pt:'dominicano',   it:'domenicano',   nl:'Dominicaans'},
  CZ:  { fr: 'tchèque',      en: 'Czech',        de: 'Tscheche',    es: 'checo',       pt: 'checo',       it: 'ceco',        nl: 'Tsjechisch' },
  RO:  { fr: 'roumaine',     en: 'Romanian',     de: 'Rumäne',      es: 'rumano',      pt: 'romeno',      it: 'rumeno',      nl: 'Roemeens' },
  GB:  { fr: 'britannique',  en: 'British',      de: 'Brite',       es: 'británico',   pt: 'britânico',   it: 'britannico',  nl: 'Brits' },
  RU:  { fr: 'russe',        en: 'Russian',      de: 'Russe',       es: 'ruso',        pt: 'russo',       it: 'russo',       nl: 'Russisch' },
  RW:  { fr: 'rwandaise',    en: 'Rwandan',      de: 'Ruander',     es: 'ruandés',     pt: 'ruandês',     it: 'ruandese',    nl: 'Rwandees' },
  KN:  { fr: 'kittitienne-et-niévicienne',en:'Kittitian or Nevisian',de:'St. Kittser',es:'sancristobaleño',pt:'cristovense',it:'kittitiano',nl:'Sint-Kittsiaans'},
  SM:  { fr: 'saint-marinaise',en:'Sammarinese', de:'San-Marineser',es:'sanmarinense',pt:'sanmarinense',it:'sammarinese',nl:'Sammarinees'},
  LC:  { fr: 'sainte-lucienne',en:'Saint Lucian',de:'St. Lucianer', es:'santalucense', pt:'santaluciano', it:'santaluciano', nl:'Sint-Luciaans'},
  VC:  { fr: 'vincentaise-et-grenadine',en:'Vincentian',de:'St. Vincente',es:'sancervantino',pt:'vicentino',it:'santvincentiano',nl:'Sint-Vincentiaans'},
  SB:  { fr: 'salomonaise',  en: 'Solomon Islander',de:'Salomoner',es:'salomonense', pt:'salomonense',  it:'salomoniano',  nl:'Salomonseilands'},
  SV:  { fr: 'salvadorienne',en: 'Salvadoran',   de: 'Salvadorianer',es:'salvadoreño', pt:'salvadorenho', it:'salvadoregno', nl:'Salvadoraans'},
  WS:  { fr: 'samoane',      en: 'Samoan',       de: 'Samoaner',    es: 'samoano',     pt: 'samoano',     it: 'samoano',     nl: 'Samoaan' },
  ST:  { fr: 'santoméenne',  en: 'São Toméan',   de: 'São-Toméer',  es: 'santomense',  pt: 'santomense',  it: 'santomense',  nl: 'Santomens' },
  SN:  { fr: 'sénégalaise',  en: 'Senegalese',   de: 'Senegalese',  es: 'senegalés',   pt: 'senegalês',   it: 'senegalese',  nl: 'Senegalees' },
  RS:  { fr: 'serbe',        en: 'Serbian',      de: 'Serbe',       es: 'serbio',      pt: 'sérvio',      it: 'serbo',       nl: 'Servisch' },
  SC:  { fr: 'seychelloise', en: 'Seychellois',  de: 'Seycheller',  es: 'seychellense',pt:'seichelense',  it:'seychellese',  nl:'Seychels'},
  SL:  { fr: 'sierra-léonaise',en:'Sierra Leonean',de:'Sierra-Leoner',es:'sierraleonés',pt:'serra-leonense',it:'sierraleonese',nl:'Sierra Leoons'},
  SG:  { fr: 'singapourienne',en: 'Singaporean',  de: 'Singapurer',  es: 'singapurense',pt:'cingapuriano', it:'singaporiano', nl:'Singaporees'},
  SK:  { fr: 'slovaque',     en: 'Slovak',       de: 'Slowake',     es: 'eslovaco',    pt: 'eslovaco',    it: 'slovacco',    nl: 'Slowaaks' },
  SI:  { fr: 'slovène',      en: 'Slovenian',    de: 'Slowene',     es: 'esloveno',    pt: 'esloveno',    it: 'sloveno',     nl: 'Sloveens' },
  SO:  { fr: 'somali',       en: 'Somali',       de: 'Somalier',    es: 'somalí',      pt: 'somali',     it: 'somalo',      nl: 'Somalisch'},
  SD:  { fr: 'soudanaise',   en: 'Sudanese',     de: 'Sudanese',    es: 'sudanés',     pt: 'sudanês',     it: 'sudanese',    nl: 'Soedanees' },
  SS:  { fr: 'sud-soudanaise',en:'South Sudanese',de:'Südsudanese', es:'sursudanés',  pt:'sul-sudanês',  it:'sud-sudanese',nl:'Zuid-Soedanees'},
  LK:  { fr: 'srilankaise',  en: 'Sri Lankan',   de: 'Sri-Lanker',  es: 'ceilanense',  pt: 'cingalês',    it: 'singalese',   nl: 'Sri Lankaans'},
  SE:  { fr: 'suédoise',     en: 'Swedish',      de: 'Schwede',     es: 'sueco',       pt: 'sueco',       it: 'svedese',     nl: 'Zweeds' },
  SR:  { fr: 'surinamaise',  en: 'Surinamese',   de: 'Surinamer',   es: 'surinamés',   pt: 'surinamês',   it: 'surinamese',  nl: 'Surinaams' },
  SY:  { fr: 'syrienne',     en: 'Syrian',       de: 'Syrer',       es: 'sirio',       pt: 'sírio',       it: 'siriano',     nl: 'Syrisch' },
  TJ:  { fr: 'tadjike',      en: 'Tajik',        de: 'Tadschike',   es: 'tayiko',      pt: 'tadjique',    it: 'tagiko',      nl: 'Tadzjieks' },
  TZ:  { fr: 'tanzanienne',  en: 'Tanzanian',    de: 'Tansanier',   es: 'tanzano',     pt: 'tanzaniano',  it: 'tanzaniano',  nl: 'Tanzaniaans' },
  TD:  { fr: 'tchadienne',   en: 'Chadian',      de: 'Tschader',    es: 'chadiano',    pt: 'chadiano',    it: 'ciadiano',    nl: 'Tsjadisch' },
  TH:  { fr: 'thaïlandaise', en: 'Thai',         de: 'Thai',        es: 'tailandés',   pt: 'tailandês',   it: 'thailandese', nl: 'Thais' },
  TL:  { fr: 'timoraise',    en: 'Timorese',     de: 'Timorese',    es: 'timorense',   pt: 'timorense',   it: 'timorense',   nl: 'Timorees' },
  TG:  { fr: 'togolaise',    en: 'Togolese',     de: 'Togolese',    es: 'togolés',     pt: 'togolês',     it: 'togolese',    nl: 'Togolees' },
  TO:  { fr: 'tonguienne',   en: 'Tongan',       de: 'Tonganer',    es: 'tongano',     pt: 'tonganês',    it: 'tongano',     nl: 'Tongaans' },
  TT:  { fr: 'trinidadienne',en: 'Trinidadian or Tobagonian',de:'Trinidadier',es:'trinitense',pt:'trinitário',it:'trinidadiano',nl:'Trinidadiaans'},
  TN:  { fr: 'tunisienne',   en: 'Tunisian',     de: 'Tunesier',    es: 'tunecino',    pt: 'tunisiano',   it: 'tunisino',    nl: 'Tunesisch' },
  TM:  { fr: 'turkmène',     en: 'Turkmen',      de: 'Turkmene',    es: 'turcomano',   pt: 'turcomeno',   it: 'turcomanno',  nl: 'Turkmeens' },
  TR:  { fr: 'turque',       en: 'Turkish',      de: 'Türke',       es: 'turco',       pt: 'turco',       it: 'turco',       nl: 'Turks' },
  TV:  { fr: 'tuvaluane',    en: 'Tuvaluan',     de: 'Tuvaluer',    es: 'tuvaluano',   pt: 'tuvaluano',   it: 'tuvaluano',   nl: 'Tuvaluaans' },
  UA:  { fr: 'ukrainienne',  en: 'Ukrainian',    de: 'Ukrainer',    es: 'ucraniano',   pt: 'ucraniano',   it: 'ucraino',     nl: 'Oekraïens' },
  UY:  { fr: 'uruguayenne',  en: 'Uruguayan',    de: 'Uruguayer',   es: 'uruguayo',    pt: 'uruguaio',    it: 'uruguaiano',  nl: 'Uruguayaans' },
  VU:  { fr: 'vanuatuane',   en: 'Ni-Vanuatu',   de: 'Vanuatu',     es: 'vanuatuense', pt: 'vanuatuense', it: 'vanuatuano',  nl: 'Vanuatuaans' },
  VA:  { fr: 'vaticane',     en: 'Vatican',      de: 'Vatikaner',   es: 'vaticano',    pt: 'vaticano',    it: 'vaticano',    nl: 'Vaticaans' },
  VE:  { fr: 'vénézuélienne',en: 'Venezuelan',   de: 'Venezolaner', es:'venezolano',   pt:'venezuelano',  it:'venezuelano',  nl:'Venezolaans'},
  VN:  { fr: 'vietnamienne', en: 'Vietnamese',   de: 'Vietnamese',  es: 'vietnamita',  pt: 'vietnamita',  it: 'vietnamita',  nl: 'Vietnamees' },
  YE:  { fr: 'yéménite',     en: 'Yemeni',       de: 'Jemenit',     es: 'yemení',      pt: 'iemenita',    it: 'yemenita',    nl: 'Jemenitisch' },
  ZM:  { fr: 'zambienne',    en: 'Zambian',      de: 'Sambier',     es: 'zambiano',    pt: 'zambiano',    it: 'zambiano',    nl: 'Zambiaans' },
  ZW:  { fr: 'zimbabwéenne', en: 'Zimbabwean',   de: 'Simbabwer',   es: 'zimbabuense', pt:'zimbabuano',   it:'zimbabwano',   nl:'Zimbabwaans'},
};

module.exports = function () {
  const result = {};
  for (const locale of LOCALES) {
    const list = COUNTRY_CODES.map(code => {
      const entry = DEMONYMS[code];
      return {
        code,
        name: entry?.[locale] || dnOf(code, locale),
      };
    });
    list.sort((a, b) => {
      if (a.code === 'CH') return -1;
      if (b.code === 'CH') return 1;
      return a.name.localeCompare(b.name, locale);
    });
    result[locale] = list;
  }
  return result;
};

const COUNTRY_CODES = [
  'CH','AF','ZA','AL','DZ','DE','AD','AO','AG','SA','AR','AM','AU','AT','AZ',
  'BS','BH','BD','BB','BE','BZ','BJ','BT','BY','MM','BO','BA','BW','BR',
  'BN','BG','BF','BI','CV','KH','CM','CA','CL','CN','CY','CO','KM','CG',
  'CD','KP','KR','CR','CI','HR','CU','DK','DJ','DM','EG','AE','EC','ER',
  'ES','EE','SZ','US','ET','FJ','FI','FR','GA','GM','GE','GH','GR','GD',
  'GT','GN','GQ','GW','GY','HT','HN','HU','IN','ID','IR','IQ','IE','IS',
  'IL','IT','JM','JP','JO','KZ','KE','KI','KW','KG','LA','LS','LV','LB',
  'LR','LY','LI','LT','LU','MK','MG','MW','MY','MV','ML','MT','MA','MH',
  'MU','MR','MX','FM','MD','MC','MN','ME','MZ','NA','NR','NP','NI','NE',
  'NG','NO','NC','NZ','OM','UG','UZ','PK','PW','PS','PA','PG','PY','NL',
  'PE','PH','PL','PT','QA','CF','DO','CZ','RO','GB','RU','RW','KN','SM',
  'LC','VC','SB','SV','WS','ST','SN','RS','SC','SL','SG','SK','SI','SO',
  'SD','SS','LK','SE','SR','SY','TJ','TZ','TD','TH','TL','TG','TO',
  'TT','TN','TM','TR','TV','UA','UY','VU','VA','VE','VN','YE','ZM','ZW',
];

const dnCache = {};
function dnOf(code, locale) {
  const key = `${locale}:${code}`;
  if (!dnCache[key]) {
    try {
      const dn = new Intl.DisplayNames([locale], { type: 'region' });
      dnCache[key] = dn.of(code);
    } catch {
      const dn = new Intl.DisplayNames(['en'], { type: 'region' });
      dnCache[key] = dn.of(code);
    }
  }
  return dnCache[key];
}
