const parkingUi = require("./booking_ui.json");

const overrides = {
  fr: {
    title: "Réservez votre studio en ligne",
    intro: "Réservation directe d'un studio près de Fribourg : choisissez vos dates et le nombre de voyageurs. Le prix se met à jour instantanément avant paiement.",
    overviewLinkLabel: "Voir les photos et équipements du studio",
    overviewLinkHref: "/fr/eco-studio/",
    datesHelp:
      "Le tarif de base inclut 1 adulte, 1 place de parking, la terrasse privative et les équipements du studio.",
    partyTitle: "Voyageurs",
    partyHelp: "Maximum 4 personnes au total, bébés inclus.",
    children: "Enfants (3-15 ans)",
    infants: "Bébés (0-2 ans)",
    showVehicle: false,
    showInfants: true,
    showWcShower: false,
    optionsTitle: "Conditions tarifaires",
    bookingRulesTitle: "Conditions importantes",
    bookingRulesList: ["Pas d'animaux", "Interdiction de fumer à l'intérieur", "Pas de fêtes"],
    nonRefundableHint: "Ce choix n'est possible que si l'arrivée est dans plus de 24 heures.",
    guestSurchargeLabel: "Suppléments voyageurs",
    wcShowerLabel: "Options",
    weeklyDiscountLabel: "Remboursement 7+ nuits",
    includedList: ["Parking gratuit pour 1 véhicule", "Terrasse privative"],
    policyFlexible: "Annulation flexible avec remboursement intégral si vous annulez plus de 48h avant l'arrivée.",
    policyNonRefundable: "Remise non remboursable : 10 % si vous choisissez volontairement ce tarif plus de 24h avant l'arrivée.",
    supportBody: "Besoin d'aide avant de réserver ? Contactez-nous via la page de contact ou WhatsApp.",
    webMcpAvailabilityToolName: "check_studio_availability",
    webMcpAvailabilityToolDescription: "Check whether the eco studio is available for a specific stay.",
    webMcpQuoteToolName: "quote_studio_stay",
    webMcpQuoteToolDescription: "Calculate a direct-booking quote for the eco studio, including extra guests and discounts.",
    webMcpCheckoutToolName: "start_studio_reservation_checkout",
    webMcpCheckoutToolDescription: "Prepare a direct reservation checkout for the eco studio, collect traveller details, create the reservation, and send the traveller to payment.",
    directBookingPromoText: "Profitez d'un avantage exclusif à notre site officiel : réservez en direct et les frais de ménage (d'une valeur de 64 CHF) sont offerts dès 5 nuits.",
    cleaningFeeLabel: "Frais de ménage",
    complimentaryLabel: "Offert"
  },
  en: {
    title: "Book your studio online",
    intro: "Direct booking for an eco studio near Fribourg: choose your dates and the number of guests. Pricing updates instantly before payment.",
    overviewLinkLabel: "See the studio photos and facilities",
    overviewLinkHref: "/en/eco-studio/",
    datesHelp:
      "The base rate includes 1 adult, free parking for 1 vehicle, the private terrace, and the studio facilities.",
    partyTitle: "Guests",
    partyHelp: "Maximum occupancy: 4 guests in total, including infants.",
    children: "Children (3-15 years)",
    infants: "Infants (0-2 years)",
    showVehicle: false,
    showInfants: true,
    showWcShower: false,
    optionsTitle: "Pricing conditions",
    bookingRulesTitle: "Important conditions",
    bookingRulesList: ["No pets", "No smoking indoors", "No parties"],
    guestSurchargeLabel: "Guest supplements",
    wcShowerLabel: "Options",
    weeklyDiscountLabel: "7+ night rebate",
    includedList: ["Free parking for 1 vehicle", "Private terrace"],
    policyFlexible: "Flexible cancellation with full refund if you cancel more than 48 hours before arrival.",
    policyNonRefundable: "Non-refundable discount: 10% if you voluntarily choose this rate more than 24 hours before arrival.",
    supportBody: "Need help before booking? Contact us through the contact page or WhatsApp.",
    webMcpAvailabilityToolName: "check_studio_availability",
    webMcpAvailabilityToolDescription: "Check whether the eco studio is available for a specific stay.",
    webMcpQuoteToolName: "quote_studio_stay",
    webMcpQuoteToolDescription: "Calculate a direct-booking quote for the eco studio, including extra guests and discounts.",
    webMcpCheckoutToolName: "start_studio_reservation_checkout",
    webMcpCheckoutToolDescription: "Prepare a direct reservation checkout for the eco studio, collect traveller details, create the reservation, and send the traveller to payment.",
    directBookingPromoText: "Enjoy a benefit exclusive to our official website: book directly and cleaning fees (worth 64 CHF) are complimentary for stays of 5 nights or more.",
    cleaningFeeLabel: "Cleaning fee",
    complimentaryLabel: "Complimentary"
  },
  de: {
    title: "Buchen Sie Ihr Studio online",
    intro: "Wählen Sie Ihre Daten und die Anzahl der Reisenden. Der Preis aktualisiert sich sofort vor der Zahlung.",
    overviewLinkLabel: "Fotos und Ausstattung des Studios ansehen",
    overviewLinkHref: "/de/eco-studio/",
    datesHelp:
      "Der Grundpreis umfasst 1 Erwachsenen, einen kostenlosen Parkplatz für 1 Fahrzeug, die private Terrasse und die Ausstattung des Studios.",
    partyTitle: "Reisende",
    partyHelp: "Maximale Belegung: 4 Personen insgesamt, Babys eingeschlossen.",
    children: "Kinder (3-15 Jahre)",
    infants: "Babys (0-2 Jahre)",
    showVehicle: false,
    showInfants: true,
    showWcShower: false,
    optionsTitle: "Preisbedingungen",
    bookingRulesTitle: "Wichtige Bedingungen",
    bookingRulesList: ["Keine Tiere", "Rauchen in Innenräumen verboten", "Keine Partys"],
    guestSurchargeLabel: "Zuschläge für Reisende",
    wcShowerLabel: "Optionen",
    weeklyDiscountLabel: "Rückvergütung ab 7 Nächten",
    includedList: ["Kostenloser Parkplatz für 1 Fahrzeug", "Private Terrasse"],
    policyFlexible: "Flexible Stornierung mit voller Erstattung bei Stornierung mehr als 48 Stunden vor Anreise.",
    policyNonRefundable: "Nicht erstattbarer Rabatt: 10 %, wenn Sie diese Rate freiwillig mehr als 24 Stunden vor Anreise wählen.",
    supportBody: "Brauchen Sie vor der Buchung Hilfe? Kontaktieren Sie uns über die Kontaktseite oder WhatsApp.",
    webMcpAvailabilityToolName: "check_studio_availability",
    webMcpAvailabilityToolDescription: "Check whether the eco studio is available for a specific stay.",
    webMcpQuoteToolName: "quote_studio_stay",
    webMcpQuoteToolDescription: "Calculate a direct-booking quote for the eco studio, including extra guests and discounts.",
    webMcpCheckoutToolName: "start_studio_reservation_checkout",
    webMcpCheckoutToolDescription: "Prepare a direct reservation checkout for the eco studio, collect traveller details, create the reservation, and send the traveller to payment.",
    directBookingPromoText: "Genießen Sie einen exklusiven Vorteil auf unserer offiziellen Website: Buchen Sie direkt und die Reinigungsgebühr (im Wert von 64 CHF) ist ab 5 Nächten kostenlos.",
    cleaningFeeLabel: "Reinigungsgebühr",
    complimentaryLabel: "Kostenlos"
  },
  es: {
    title: "Reserva tu estudio en linea",
    intro: "Elige tus fechas y el número de viajeros. El precio se actualiza al instante antes del pago.",
    overviewLinkLabel: "Ver fotos y equipamiento del estudio",
    overviewLinkHref: "/es/eco-studio/",
    datesHelp:
      "La tarifa base incluye 1 adulto, aparcamiento gratuito para 1 vehículo, la terraza privada y el equipamiento del estudio.",
    partyTitle: "Viajeros",
    partyHelp: "Capacidad máxima: 4 personas en total, bebés incluidos.",
    children: "Niños (3-15 años)",
    infants: "Bebés (0-2 años)",
    showVehicle: false,
    showInfants: true,
    showWcShower: false,
    optionsTitle: "Condiciones tarifarias",
    bookingRulesTitle: "Condiciones importantes",
    bookingRulesList: ["No se admiten animales", "Prohibido fumar en el interior", "No fiestas"],
    guestSurchargeLabel: "Suplementos de viajeros",
    wcShowerLabel: "Opciones",
    weeklyDiscountLabel: "Reembolso desde 7 noches",
    includedList: ["Parking gratuito para 1 vehículo", "Terraza privada"],
    policyFlexible: "Cancelación flexible con reembolso total si cancelas más de 48 horas antes de la llegada.",
    policyNonRefundable: "Descuento no reembolsable: 10 % si eliges voluntariamente esta tarifa más de 24 horas antes de la llegada.",
    supportBody: "¿Necesitas ayuda antes de reservar? Contáctanos por la página de contacto o por WhatsApp.",
    webMcpAvailabilityToolName: "check_studio_availability",
    webMcpAvailabilityToolDescription: "Check whether the eco studio is available for a specific stay.",
    webMcpQuoteToolName: "quote_studio_stay",
    webMcpQuoteToolDescription: "Calculate a direct-booking quote for the eco studio, including extra guests and discounts.",
    webMcpCheckoutToolName: "start_studio_reservation_checkout",
    webMcpCheckoutToolDescription: "Prepare a direct reservation checkout for the eco studio, collect traveller details, create the reservation, and send the traveller to payment.",
    directBookingPromoText: "Disfrute de una ventaja exclusiva de nuestro sitio web oficial: reserve directamente y los gastos de limpieza (valorados en 64 CHF) son gratuitos para estancias de 5 noches o más.",
    cleaningFeeLabel: "Gastos de limpieza",
    complimentaryLabel: "Cortesía"
  },
  pt: {
    title: "Reserve o seu estudio online",
    intro: "Escolha as suas datas e o número de viajantes. O preço atualiza-se instantaneamente antes do pagamento.",
    overviewLinkLabel: "Ver fotos e equipamentos do estúdio",
    overviewLinkHref: "/pt/eco-studio/",
    datesHelp:
      "A tarifa base inclui 1 adulto, estacionamento gratuito para 1 veículo, o terraço privativo e os equipamentos do estúdio.",
    partyTitle: "Viajantes",
    partyHelp: "Capacidade máxima: 4 pessoas no total, incluindo bebés.",
    children: "Crianças (3-15 anos)",
    infants: "Bebés (0-2 anos)",
    showVehicle: false,
    showInfants: true,
    showWcShower: false,
    optionsTitle: "Condições tarifárias",
    bookingRulesTitle: "Condições importantes",
    bookingRulesList: ["Animais não permitidos", "Proibido fumar no interior", "Sem festas"],
    guestSurchargeLabel: "Suplementos de viajantes",
    wcShowerLabel: "Opções",
    weeklyDiscountLabel: "Reembolso a partir de 7 noites",
    includedList: ["Estacionamento gratuito para 1 veículo", "Terraço privativo"],
    policyFlexible: "Cancelamento flexível com reembolso total se cancelar mais de 48 horas antes da chegada.",
    policyNonRefundable: "Desconto não reembolsável: 10% se escolher voluntariamente esta tarifa mais de 24 horas antes da chegada.",
    supportBody: "Precisa de ajuda antes de reservar? Contacte-nos pela página de contacto ou pelo WhatsApp.",
    webMcpAvailabilityToolName: "check_studio_availability",
    webMcpAvailabilityToolDescription: "Check whether the eco studio is available for a specific stay.",
    webMcpQuoteToolName: "quote_studio_stay",
    webMcpQuoteToolDescription: "Calculate a direct-booking quote for the eco studio, including extra guests and discounts.",
    webMcpCheckoutToolName: "start_studio_reservation_checkout",
    webMcpCheckoutToolDescription: "Prepare a direct reservation checkout for the eco studio, collect traveller details, create the reservation, and send the traveller to payment.",
    directBookingPromoText: "Desfrute de uma vantagem exclusiva do nosso website oficial: reserve diretamente e a taxa de limpeza (no valor de 64 CHF) é gratuita para estadias de 5 noites ou mais.",
    cleaningFeeLabel: "Taxa de limpeza",
    complimentaryLabel: "Cortesia"
  },
  it: {
    title: "Prenota il tuo studio online",
    intro: "Scegli le date e il numero di viaggiatori. Il prezzo si aggiorna istantaneamente prima del pagamento.",
    overviewLinkLabel: "Vedi foto e dotazioni dello studio",
    overviewLinkHref: "/it/eco-studio/",
    datesHelp:
      "La tariffa base include 1 adulto, parcheggio gratuito per 1 veicolo, terrazza privata e dotazioni dello studio.",
    partyTitle: "Viaggiatori",
    partyHelp: "Occupazione massima: 4 persone in totale, neonati inclusi.",
    children: "Bambini (3-15 anni)",
    infants: "Neonati (0-2 anni)",
    showVehicle: false,
    showInfants: true,
    showWcShower: false,
    optionsTitle: "Condizioni tariffarie",
    bookingRulesTitle: "Condizioni importanti",
    bookingRulesList: ["Animali non ammessi", "Vietato fumare all'interno", "Niente feste"],
    guestSurchargeLabel: "Supplementi viaggiatori",
    wcShowerLabel: "Opzioni",
    weeklyDiscountLabel: "Rimborso da 7 notti",
    includedList: ["Parcheggio gratuito per 1 veicolo", "Terrazza privata"],
    policyFlexible: "Cancellazione flessibile con rimborso completo se annulli più di 48 ore prima dell'arrivo.",
    policyNonRefundable: "Sconto non rimborsabile: 10% se scegli volontariamente questa tariffa più di 24 ore prima dell'arrivo.",
    supportBody: "Hai bisogno di aiuto prima di prenotare? Contattaci tramite la pagina contatti o WhatsApp.",
    webMcpAvailabilityToolName: "check_studio_availability",
    webMcpAvailabilityToolDescription: "Check whether the eco studio is available for a specific stay.",
    webMcpQuoteToolName: "quote_studio_stay",
    webMcpQuoteToolDescription: "Calculate a direct-booking quote for the eco studio, including extra guests and discounts.",
    webMcpCheckoutToolName: "start_studio_reservation_checkout",
    webMcpCheckoutToolDescription: "Prepare a direct reservation checkout for the eco studio, collect traveller details, create the reservation, and send the traveller to payment.",
    directBookingPromoText: "Approfitta di un vantaggio esclusivo del nostro sito ufficiale: prenota direttamente e le spese di pulizia (del valore di 64 CHF) sono offerte per soggiorni di 5 o più notti.",
    cleaningFeeLabel: "Spese di pulizia",
    complimentaryLabel: "Offerto"
  },
  nl: {
    title: "Boek je studio online",
    intro: "Kies je data en het aantal reizigers. De prijs wordt direct bijgewerkt vóór betaling.",
    overviewLinkLabel: "Bekijk foto's en voorzieningen van de studio",
    overviewLinkHref: "/nl/eco-studio/",
    datesHelp:
      "Het basistarief omvat 1 volwassene, gratis parking voor 1 voertuig, het privéterras en de studio-uitrusting.",
    partyTitle: "Reizigers",
    partyHelp: "Maximale bezetting: 4 personen in totaal, inclusief baby's.",
    children: "Kinderen (3-15 jaar)",
    infants: "Baby's (0-2 jaar)",
    showVehicle: false,
    showInfants: true,
    showWcShower: false,
    optionsTitle: "Tariefvoorwaarden",
    bookingRulesTitle: "Belangrijke voorwaarden",
    bookingRulesList: ["Geen huisdieren", "Niet roken binnen", "Geen feesten"],
    guestSurchargeLabel: "Toeslagen reizigers",
    wcShowerLabel: "Opties",
    weeklyDiscountLabel: "Terugbetaling vanaf 7 nachten",
    includedList: ["Gratis parking voor 1 voertuig", "Privéterras"],
    policyFlexible: "Flexibele annulering met volledige terugbetaling als je meer dan 48 uur voor aankomst annuleert.",
    policyNonRefundable: "Niet-terugbetaalbare korting: 10% als je vrijwillig dit tarief kiest meer dan 24 uur voor aankomst.",
    supportBody: "Hulp nodig vóór het boeken? Neem contact met ons op via de contactpagina of WhatsApp.",
    webMcpAvailabilityToolName: "check_studio_availability",
    webMcpAvailabilityToolDescription: "Check whether the eco studio is available for a specific stay.",
    webMcpQuoteToolName: "quote_studio_stay",
    webMcpQuoteToolDescription: "Calculate a direct-booking quote for the eco studio, including extra guests and discounts.",
    webMcpCheckoutToolName: "start_studio_reservation_checkout",
    webMcpCheckoutToolDescription: "Prepare a direct reservation checkout for the eco studio, collect traveller details, create the reservation, and send the traveller to payment.",
    directBookingPromoText: "Geniet van een exclusief voordeel op onze officiële website: boek rechtstreeks en de schoonmaakkosten (t.w.v. 64 CHF) zijn gratis bij een verblijf van 5 nachten of meer.",
    cleaningFeeLabel: "Schoonmaakkosten",
    complimentaryLabel: "Gratis"
  }
};

module.exports = Object.fromEntries(
  Object.entries(parkingUi).map(([locale, base]) => {
    const override = overrides[locale] || overrides.en;
    return [
      locale,
      {
        ...base,
        ...override,
      },
    ];
  }),
);
